<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.1+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.89196982, 0.08917743, 0.00402986, 0.5346448 , 0.49578615],
        [0.89864445, 0.63864194, 0.29701842, 0.06862793, 0.18066981],
        [0.88591058, 0.71017151, 0.08116017, 0.50022614, 0.58129563],
        [0.74409848, 0.77784056, 0.2313471 , 0.83569856, 0.22919469],
        [0.7631359 , 0.16746806, 0.67742055, 0.01612629, 0.04092737]],

       [[0.03274766, 0.49618335, 0.12698889, 0.31700192, 0.82564683],
        [0.00132913, 0.24023505, 0.77631877, 0.82543973, 0.9828253 ],
        [0.07455777, 0.7024574 , 0.06909127, 0.24095883, 0.84671914],
        [0.73749673, 0.5338582 , 0.0068573 , 0.3392588 , 0.37790612],
        [0.15600209, 0.39899356, 0.1266619 , 0.66284574, 0.91464488]],

       [[0.22547766, 0.39074562, 0.58767645, 0.03318259, 0.84967212],
        [0.71184559, 0.69943763, 0.29244203, 0.68550337, 0.86771511],
        [0.41246062, 0.67201053, 0.71458715, 0.53496412, 0.83050723],
        [0.44938524, 0.76294174, 0.37507355, 0.36966675, 0.52872052],
        [0.04722

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [7]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [8]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d * 10)

tensor_2d
 tensor([[0.3081, 7.9435, 7.3663, 7.9821],
        [0.4695, 8.6213, 9.7319, 0.5229],
        [9.6212, 6.1651, 3.1396, 2.7598]])


In [9]:
testing = torch.tensor([1,2.,3],  requires_grad=True, device=torch.device('cpu'))
threads = torch.get_num_threads()
print('Number of threads :',threads)
testing

Number of threads : 1


tensor([1., 2., 3.], requires_grad=True)

In [10]:
check_grad = torch.is_grad_enabled()
print(check_grad)
torch.no_grad()
print(torch.is_grad_enabled())


True
True


In [11]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.8920, 0.0892, 0.0040, 0.5346, 0.4958],
         [0.8986, 0.6386, 0.2970, 0.0686, 0.1807],
         [0.8859, 0.7102, 0.0812, 0.5002, 0.5813],
         [0.7441, 0.7778, 0.2313, 0.8357, 0.2292],
         [0.7631, 0.1675, 0.6774, 0.0161, 0.0409]],

        [[0.0327, 0.4962, 0.1270, 0.3170, 0.8256],
         [0.0013, 0.2402, 0.7763, 0.8254, 0.9828],
         [0.0746, 0.7025, 0.0691, 0.2410, 0.8467],
         [0.7375, 0.5339, 0.0069, 0.3393, 0.3779],
         [0.1560, 0.3990, 0.1267, 0.6628, 0.9146]],

        [[0.2255, 0.3907, 0.5877, 0.0332, 0.8497],
         [0.7118, 0.6994, 0.2924, 0.6855, 0.8677],
         [0.4125, 0.6720, 0.7146, 0.5350, 0.8305],
         [0.4494, 0.7629, 0.3751, 0.3697, 0.5287],
         [0.0472, 0.2136, 0.7523, 0.8532, 0.1841]]], dtype=torch.float64)

In [13]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [14]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [15]:
r = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(r[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])

tensor(4)
[[0.41946324 0.92685697 0.08844468]
 [0.55036156 0.98328885 0.85081612]]
0.9832888534037219
tensor(0.9833, dtype=torch.float64)


In [16]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.75231134 0.1487681  0.99873881]
 [0.78604011 0.31668438 0.70456552]]
0.3166843778376063
tensor(0.3167, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [17]:
x = torch.tensor([[1]])
x
x.item()

1

In [18]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [19]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [20]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


In [32]:
gpu
gpu = torch.device('cuda:0')
gpu

device(type='cuda', index=0)

**Basic Math Operations**

In [21]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [22]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])

In [23]:
my_tensor = torch.randn(3)
print(my_tensor)
my_tensor = torch.mul(my_tensor, 100)
my_tensor = torch.abs(my_tensor)    # Get the absolute value
# my_tensor = torch.mul(my_tensor, 100)
# my_tensor
print('Rounded values : ',torch.round(my_tensor))
torch.max(my_tensor)

tensor([-0.5208, -0.0527, -0.5132])
Rounded values :  tensor([52.,  5., 51.])


tensor(52.0773)

In [24]:
prod_this = torch.tensor([1,2,3,4,5])
torch.prod(prod_this)
seven20 = torch.arange(1,7)
seven20
print(torch.prod(seven20))

# count non-zero
print(torch.count_nonzero(prod_this))


tensor(720)
tensor(5)


Sort

In [25]:
torch.sort(prod_this, descending=False)     #descending=False we can change it to True

torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 1, 2, 3, 4]))

In [26]:
torch.tensor([1,2,3,4,5,6]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
torch.cuda.get_device_properties(torch.cuda.get_device_name)

torch.cuda.get_device_capability(torch.cuda.get_device_name)
torch.cuda.is_available()
torch.cuda.is_initialized()
print('memory allocated : ',torch.cuda.memory_allocated())
print('memory usage: ', torch.cuda.memory_cached)
torch.cuda.power_draw

memory allocated :  512
memory usage:  <function memory_cached at 0x7982b633e4d0>


<function torch.cuda.power_draw(device: Union[torch.device, str, int, NoneType] = None) -> int>

In [28]:
a = torch.tensor(torch.rand(50))

shape = torch.reshape(a, (5,10))
shape.shape

<ipython-input-28-0d7fd5271b5f>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(torch.rand(50))


torch.Size([5, 10])

**CPU**

In [29]:
torch.cpu.current_device()
torch.cpu.device_count

<function torch.cpu.device_count() -> int>

In [42]:
y_arr = torch.tensor([[15,12],[12,8]])
print(y_arr)

tensor([[15, 12],
        [12,  8]])


**!!! Pytorch Practice Session Covered all the necessary basic operations in Pytorch Library  !!!**