<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.4.0+cu121


In [ ]:
mylist = [[1,2,3],[4,5,6]]
print(mylist)

np1 = np.random.rand(3,4)
print(np1)

[[1, 2, 3], [4, 5, 6]]
[[0.31274245 0.01295069 0.48438924 0.35319804]
 [0.37935028 0.37052245 0.10197087 0.41065625]
 [0.90717634 0.65850171 0.99172456 0.47219955]]
