<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.1+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.32009499, 0.095237  , 0.43790816, 0.26421476, 0.3242267 ],
        [0.05143639, 0.68989192, 0.00113116, 0.67273965, 0.31476431],
        [0.89694568, 0.79404487, 0.99579772, 0.91239119, 0.22537087],
        [0.58827547, 0.89065089, 0.93024255, 0.91016683, 0.3838542 ],
        [0.24898137, 0.72424161, 0.2472635 , 0.003079  , 0.27344315]],

       [[0.73473866, 0.66235077, 0.73978761, 0.2247359 , 0.29918405],
        [0.02900649, 0.40821577, 0.92675823, 0.17736635, 0.98947002],
        [0.56141454, 0.53945129, 0.72633495, 0.85106542, 0.05428161],
        [0.57392586, 0.33582027, 0.49584769, 0.12404809, 0.13585053],
        [0.59656084, 0.94844158, 0.61652827, 0.63087781, 0.78286814]],

       [[0.53814513, 0.21465881, 0.39086707, 0.871644  , 0.85603067],
        [0.0827619 , 0.92372051, 0.49003807, 0.15899348, 0.28885169],
        [0.21057632, 0.86880276, 0.21152123, 0.99541022, 0.4346262 ],
        [0.52046952, 0.50577542, 0.79660426, 0.71743302, 0.62209207],
        [0.42133

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [7]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [8]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d * 10)

tensor_2d
 tensor([[8.4748, 0.9884, 0.2945, 2.1477],
        [4.7583, 0.8050, 3.9603, 3.5607],
        [0.0482, 1.8726, 8.0177, 5.9640]])


In [9]:
testing = torch.tensor([1,2.,3],  requires_grad=True, device=torch.device('cpu'))
threads = torch.get_num_threads()
print('Number of threads :',threads)
testing

Number of threads : 1


tensor([1., 2., 3.], requires_grad=True)

In [10]:
check_grad = torch.is_grad_enabled()
print(check_grad)
torch.no_grad()
print(torch.is_grad_enabled())


True
True


In [11]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.3201, 0.0952, 0.4379, 0.2642, 0.3242],
         [0.0514, 0.6899, 0.0011, 0.6727, 0.3148],
         [0.8969, 0.7940, 0.9958, 0.9124, 0.2254],
         [0.5883, 0.8907, 0.9302, 0.9102, 0.3839],
         [0.2490, 0.7242, 0.2473, 0.0031, 0.2734]],

        [[0.7347, 0.6624, 0.7398, 0.2247, 0.2992],
         [0.0290, 0.4082, 0.9268, 0.1774, 0.9895],
         [0.5614, 0.5395, 0.7263, 0.8511, 0.0543],
         [0.5739, 0.3358, 0.4958, 0.1240, 0.1359],
         [0.5966, 0.9484, 0.6165, 0.6309, 0.7829]],

        [[0.5381, 0.2147, 0.3909, 0.8716, 0.8560],
         [0.0828, 0.9237, 0.4900, 0.1590, 0.2889],
         [0.2106, 0.8688, 0.2115, 0.9954, 0.4346],
         [0.5205, 0.5058, 0.7966, 0.7174, 0.6221],
         [0.4213, 0.1449, 0.8108, 0.2528, 0.5101]]], dtype=torch.float64)

In [13]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [14]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

Content can be accessed and modified using slice and indexing

In [15]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.76201738 0.4029238  0.71026606]
 [0.57895191 0.8505963  0.34881784]]
0.8505963031500745
tensor(0.8506, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [16]:
x = torch.tensor([[1]])
x
x.item()

1

In [17]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [18]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [19]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Basic Math Operations**

In [20]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [21]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])

In [49]:
my_tensor = torch.randn(3)
print(my_tensor)
my_tensor = torch.mul(my_tensor, 100)
my_tensor = torch.abs(my_tensor)    # Get the absolute value
# my_tensor = torch.mul(my_tensor, 100)
# my_tensor
print('Rounded values : ',torch.round(my_tensor))
torch.max(my_tensor)

tensor([-0.2379,  0.7699,  0.9192])
Rounded values :  tensor([24., 77., 92.])


tensor(91.9165)

In [52]:
prod_this = torch.tensor([1,2,3,4,5])
torch.prod(prod_this)
seven20 = torch.arange(1,7)
seven20
torch.prod(seven20)

tensor(720)