<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.1+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.57290046, 0.16304636, 0.2696101 , 0.07957552, 0.12024743],
        [0.44125492, 0.28952246, 0.46413736, 0.78291272, 0.70611837],
        [0.50213554, 0.91864375, 0.92629704, 0.22350137, 0.5546104 ],
        [0.40900745, 0.52006024, 0.40215551, 0.37598782, 0.14580073],
        [0.76912505, 0.05771405, 0.41202431, 0.61542697, 0.72440162]],

       [[0.12586294, 0.66093066, 0.99326651, 0.9029988 , 0.95719969],
        [0.74777989, 0.88052087, 0.24180121, 0.88638114, 0.36262114],
        [0.56329982, 0.16355839, 0.60670069, 0.96954604, 0.46271486],
        [0.12701994, 0.69654169, 0.24970385, 0.90048026, 0.76174318],
        [0.71369174, 0.99678991, 0.42742288, 0.34662711, 0.1578469 ]],

       [[0.9845982 , 0.36116946, 0.45001073, 0.75215716, 0.35589737],
        [0.4243195 , 0.74598119, 0.65096944, 0.18426227, 0.67449381],
        [0.53016613, 0.29821686, 0.36688105, 0.08286045, 0.12645994],
        [0.44243302, 0.62599661, 0.15324023, 0.67652261, 0.94034354],
        [0.30694

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [7]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [8]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d * 10)

tensor_2d
 tensor([[2.8624, 4.3104, 4.5251, 3.7129],
        [2.5312, 9.3245, 8.6381, 3.8879],
        [8.4489, 5.0756, 4.3292, 0.0179]])


In [9]:
testing = torch.tensor([1,2.,3],  requires_grad=True, device=torch.device('cpu'))
threads = torch.get_num_threads()
print('Number of threads :',threads)
testing

Number of threads : 1


tensor([1., 2., 3.], requires_grad=True)

In [10]:
check_grad = torch.is_grad_enabled()
print(check_grad)
torch.no_grad()
print(torch.is_grad_enabled())


True
True


In [11]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.5729, 0.1630, 0.2696, 0.0796, 0.1202],
         [0.4413, 0.2895, 0.4641, 0.7829, 0.7061],
         [0.5021, 0.9186, 0.9263, 0.2235, 0.5546],
         [0.4090, 0.5201, 0.4022, 0.3760, 0.1458],
         [0.7691, 0.0577, 0.4120, 0.6154, 0.7244]],

        [[0.1259, 0.6609, 0.9933, 0.9030, 0.9572],
         [0.7478, 0.8805, 0.2418, 0.8864, 0.3626],
         [0.5633, 0.1636, 0.6067, 0.9695, 0.4627],
         [0.1270, 0.6965, 0.2497, 0.9005, 0.7617],
         [0.7137, 0.9968, 0.4274, 0.3466, 0.1578]],

        [[0.9846, 0.3612, 0.4500, 0.7522, 0.3559],
         [0.4243, 0.7460, 0.6510, 0.1843, 0.6745],
         [0.5302, 0.2982, 0.3669, 0.0829, 0.1265],
         [0.4424, 0.6260, 0.1532, 0.6765, 0.9403],
         [0.3069, 0.1645, 0.2020, 0.9947, 0.3277]]], dtype=torch.float64)

In [13]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [14]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [51]:
r = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(r[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])

tensor(4)
[[0.88362924 0.30609147 0.95894929]
 [0.70694549 0.06913644 0.86359944]]
0.06913644044355638
tensor(0.0691, dtype=torch.float64)


In [15]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.92255296 0.18464743 0.35798547]
 [0.23103431 0.0813273  0.29425373]]
0.08132729944878447
tensor(0.0813, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [16]:
x = torch.tensor([[1]])
x
x.item()

1

In [17]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [18]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [19]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


**Basic Math Operations**

In [20]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [21]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])

In [22]:
my_tensor = torch.randn(3)
print(my_tensor)
my_tensor = torch.mul(my_tensor, 100)
my_tensor = torch.abs(my_tensor)    # Get the absolute value
# my_tensor = torch.mul(my_tensor, 100)
# my_tensor
print('Rounded values : ',torch.round(my_tensor))
torch.max(my_tensor)

tensor([ 0.1890, -0.0960, -1.1647])
Rounded values :  tensor([ 19.,  10., 116.])


tensor(116.4658)

In [23]:
prod_this = torch.tensor([1,2,3,4,5])
torch.prod(prod_this)
seven20 = torch.arange(1,7)
seven20
print(torch.prod(seven20))

# count non-zero
print(torch.count_nonzero(prod_this))


tensor(720)
tensor(5)


Sort

In [24]:
torch.sort(prod_this, descending=False)     #descending=False we can change it to True

torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 1, 2, 3, 4]))

In [44]:
torch.cuda.get_device_properties(torch.cuda.get_device_name)

torch.cuda.get_device_capability(torch.cuda.get_device_name)
torch.cuda.is_available()
torch.cuda.is_initialized()
print('memory allocated : ',torch.cuda.memory_allocated())
print('memory usage: ', torch.cuda.memory_cached)
torch.cuda.power_draw

memory allocated :  512
memory usage:  <function memory_cached at 0x7c8c70b42320>


<function torch.cuda.power_draw(device: Union[torch.device, str, int, NoneType] = None) -> int>

In [50]:
a = torch.tensor(torch.rand(50))

shape = torch.reshape(a, (5,10))
shape.shape

<ipython-input-50-0d7fd5271b5f>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(torch.rand(50))


torch.Size([5, 10])

**CPU**

In [57]:
torch.cpu.current_device()
torch.cpu.device_count

<function torch.cpu.device_count() -> int>