<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

**Pytorch basics**

In [ ]:
print(torch.__version__)

2.4.0+cu121


In [ ]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,4)
np1


array([[0.03537417, 0.00289237, 0.63428392, 0.72477867],
       [0.08484962, 0.5897789 , 0.70281749, 0.79880552],
       [0.32998325, 0.09015048, 0.81478014, 0.04599603]])

In [ ]:
print(np1.dtype)

float64


In [ ]:
tensor_2d = torch.rand(3,4)
print(tensor_2d.dtype)
tensor_2d


torch.float32


tensor([[0.3443, 0.5810, 0.8273, 0.2734],
        [0.1811, 0.2277, 0.4672, 0.1770],
        [0.1084, 0.8196, 0.5005, 0.2053]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[0.0354, 0.0029, 0.6343, 0.7248],
        [0.0848, 0.5898, 0.7028, 0.7988],
        [0.3300, 0.0902, 0.8148, 0.0460]], dtype=torch.float64)

In [ ]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3], dtype=torch.int32)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
print(cuda0)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
cuda:0


In [ ]:
#Content can be accessed and modified using python slicing and indexing notations
x = torch.tensor([[1,2,3], [4,5,6]])
y = np.array([1,2,4])
y

array([1, 2, 4])

In [ ]:
import math

In [ ]:
myl = np.array([[2,2,3,4,5],
                [2,2,3,4,5]])

myl.ndim #Return number of dimensions
myl.shape # Return number of elements in each dimension   (2,5)
len(myl.shape) == myl.ndim  # Is it the same as no. of dimensions?
myl.size   # Total number of elements  (10)
math.prod(myl.shape) == myl.size    # no. of elements is each dimension * no. of dimensions

myl.dtype


dtype('int64')

**Create a basic array**

In [ ]:
array = np.zeros([2,3])
array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
array_ones = np.ones([3,2], dtype=int)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
# Empty array
array_emt = np.empty(3)  #Because of speed
array_emt

array([4.69791869e-310, 0.00000000e+000, 1.58101007e-322])

In [ ]:
# Range of elements
