<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.0+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.20365646, 0.19682859, 0.38273417, 0.17155242, 0.52871662],
        [0.62995862, 0.66121419, 0.12826479, 0.31272057, 0.0796978 ],
        [0.44492914, 0.96619171, 0.23561065, 0.07762357, 0.02035758],
        [0.94768684, 0.96250074, 0.76274884, 0.30523859, 0.43834296],
        [0.56072966, 0.91875762, 0.94455126, 0.12533995, 0.57600906]],

       [[0.58497319, 0.7178339 , 0.10789482, 0.46124055, 0.58561243],
        [0.8433209 , 0.63376587, 0.27714225, 0.35172224, 0.91520466],
        [0.28808694, 0.90999761, 0.63166372, 0.21325524, 0.56494902],
        [0.47457783, 0.0516738 , 0.74427904, 0.7299633 , 0.32048726],
        [0.17763692, 0.93129479, 0.80951073, 0.29055366, 0.36329425]],

       [[0.52880484, 0.31358789, 0.95417606, 0.22230377, 0.66144358],
        [0.19371523, 0.99824275, 0.35110234, 0.57156655, 0.32935822],
        [0.98401537, 0.23213879, 0.49787918, 0.46192333, 0.60835557],
        [0.80772338, 0.59716795, 0.51037714, 0.51125615, 0.4027377 ],
        [0.53496

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d)

tensor_2d
 tensor([[0.7219, 0.9594, 0.5217, 0.9493],
        [0.5888, 0.6289, 0.7517, 0.7634],
        [0.0967, 0.4309, 0.8986, 0.8650]])


In [7]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.2037, 0.1968, 0.3827, 0.1716, 0.5287],
         [0.6300, 0.6612, 0.1283, 0.3127, 0.0797],
         [0.4449, 0.9662, 0.2356, 0.0776, 0.0204],
         [0.9477, 0.9625, 0.7627, 0.3052, 0.4383],
         [0.5607, 0.9188, 0.9446, 0.1253, 0.5760]],

        [[0.5850, 0.7178, 0.1079, 0.4612, 0.5856],
         [0.8433, 0.6338, 0.2771, 0.3517, 0.9152],
         [0.2881, 0.9100, 0.6317, 0.2133, 0.5649],
         [0.4746, 0.0517, 0.7443, 0.7300, 0.3205],
         [0.1776, 0.9313, 0.8095, 0.2906, 0.3633]],

        [[0.5288, 0.3136, 0.9542, 0.2223, 0.6614],
         [0.1937, 0.9982, 0.3511, 0.5716, 0.3294],
         [0.9840, 0.2321, 0.4979, 0.4619, 0.6084],
         [0.8077, 0.5972, 0.5104, 0.5113, 0.4027],
         [0.5350, 0.0754, 0.9702, 0.6719, 0.8688]]], dtype=torch.float64)

In [9]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [10]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [30]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.23241768 0.04987239 0.19413608]
 [0.20758609 0.40717119 0.12858399]]
0.4071711942967885
tensor(0.4072, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [27]:
x = torch.tensor([[1]])
x
x.item()

1

In [35]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [40]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 8., -8.],
        [ 8.,  8.]])