<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.0+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.94856106, 0.31897173, 0.67718983, 0.54431131, 0.15047465],
        [0.53180112, 0.90640311, 0.76948487, 0.66936463, 0.51773982],
        [0.91159798, 0.22229462, 0.90864842, 0.45192912, 0.65541678],
        [0.41203949, 0.82885632, 0.73123457, 0.09470693, 0.63401432],
        [0.02602764, 0.5527561 , 0.29145815, 0.12867228, 0.95493016]],

       [[0.49272303, 0.07256741, 0.25155679, 0.37699721, 0.01932041],
        [0.47532207, 0.55337696, 0.75591096, 0.94545102, 0.81611688],
        [0.53909853, 0.37584044, 0.42594131, 0.24727602, 0.35987514],
        [0.14762025, 0.19676839, 0.91736292, 0.35393006, 0.55194439],
        [0.46167414, 0.08197013, 0.91189746, 0.67489949, 0.62503106]],

       [[0.55731221, 0.22778974, 0.85787942, 0.42238919, 0.52698078],
        [0.0153719 , 0.03624964, 0.56143486, 0.16561464, 0.84061066],
        [0.40789642, 0.17944832, 0.38747084, 0.26049908, 0.78400058],
        [0.15630297, 0.15240669, 0.65677809, 0.11171625, 0.21867464],
        [0.58746

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [33]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [31]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [6]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d)

tensor_2d
 tensor([[0.4460, 0.8536, 0.2214, 0.4286],
        [0.7192, 0.1617, 0.2713, 0.5714],
        [0.2207, 0.7046, 0.7586, 0.5322]])


In [7]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.9486, 0.3190, 0.6772, 0.5443, 0.1505],
         [0.5318, 0.9064, 0.7695, 0.6694, 0.5177],
         [0.9116, 0.2223, 0.9086, 0.4519, 0.6554],
         [0.4120, 0.8289, 0.7312, 0.0947, 0.6340],
         [0.0260, 0.5528, 0.2915, 0.1287, 0.9549]],

        [[0.4927, 0.0726, 0.2516, 0.3770, 0.0193],
         [0.4753, 0.5534, 0.7559, 0.9455, 0.8161],
         [0.5391, 0.3758, 0.4259, 0.2473, 0.3599],
         [0.1476, 0.1968, 0.9174, 0.3539, 0.5519],
         [0.4617, 0.0820, 0.9119, 0.6749, 0.6250]],

        [[0.5573, 0.2278, 0.8579, 0.4224, 0.5270],
         [0.0154, 0.0362, 0.5614, 0.1656, 0.8406],
         [0.4079, 0.1794, 0.3875, 0.2605, 0.7840],
         [0.1563, 0.1524, 0.6568, 0.1117, 0.2187],
         [0.5875, 0.7473, 0.9746, 0.3488, 0.7902]]], dtype=torch.float64)

In [9]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [10]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [11]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.78382261 0.93513598 0.63744038]
 [0.64500592 0.88683364 0.82597335]]
0.886833635665953
tensor(0.8868, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [12]:
x = torch.tensor([[1]])
x
x.item()

1

In [13]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [14]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [15]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


**Basic Math Operations**

In [16]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [17]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])