<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.0+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.57239361, 0.02321355, 0.60929096, 0.00927609, 0.51166865],
        [0.11273355, 0.49906833, 0.16424528, 0.56974699, 0.09046533],
        [0.02624935, 0.49778282, 0.71159684, 0.62802442, 0.76383417],
        [0.00304927, 0.64708213, 0.41732963, 0.95137817, 0.84031083],
        [0.58409879, 0.00214659, 0.52229993, 0.14687111, 0.84563983]],

       [[0.24738946, 0.46587714, 0.21261117, 0.26865979, 0.85751701],
        [0.89492097, 0.73628511, 0.7195711 , 0.11822864, 0.44115334],
        [0.76738913, 0.4080444 , 0.20215991, 0.15979268, 0.60565616],
        [0.99540538, 0.69326267, 0.76420851, 0.03111385, 0.34494149],
        [0.87716688, 0.54673724, 0.44784888, 0.62818122, 0.99814032]],

       [[0.42742997, 0.75348869, 0.26833648, 0.31617229, 0.41601263],
        [0.11863766, 0.54590515, 0.67737688, 0.93346537, 0.63989079],
        [0.9868384 , 0.19126947, 0.17333111, 0.88481679, 0.28597285],
        [0.58881237, 0.52361356, 0.81006824, 0.73656594, 0.02246491],
        [0.08476

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d)

tensor_2d
 tensor([[0.1962, 0.5169, 0.2555, 0.3607],
        [0.3695, 0.8744, 0.8562, 0.5838],
        [0.3181, 0.8813, 0.1285, 0.7333]])


In [7]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.5724, 0.0232, 0.6093, 0.0093, 0.5117],
         [0.1127, 0.4991, 0.1642, 0.5697, 0.0905],
         [0.0262, 0.4978, 0.7116, 0.6280, 0.7638],
         [0.0030, 0.6471, 0.4173, 0.9514, 0.8403],
         [0.5841, 0.0021, 0.5223, 0.1469, 0.8456]],

        [[0.2474, 0.4659, 0.2126, 0.2687, 0.8575],
         [0.8949, 0.7363, 0.7196, 0.1182, 0.4412],
         [0.7674, 0.4080, 0.2022, 0.1598, 0.6057],
         [0.9954, 0.6933, 0.7642, 0.0311, 0.3449],
         [0.8772, 0.5467, 0.4478, 0.6282, 0.9981]],

        [[0.4274, 0.7535, 0.2683, 0.3162, 0.4160],
         [0.1186, 0.5459, 0.6774, 0.9335, 0.6399],
         [0.9868, 0.1913, 0.1733, 0.8848, 0.2860],
         [0.5888, 0.5236, 0.8101, 0.7366, 0.0225],
         [0.0848, 0.7942, 0.8347, 0.3793, 0.9997]]], dtype=torch.float64)

In [9]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [10]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [11]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.49060788 0.26008314 0.52455032]
 [0.84899131 0.01378224 0.53647772]]
0.013782244102899077
tensor(0.0138, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [12]:
x = torch.tensor([[1]])
x
x.item()

1

In [13]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [14]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [15]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


**Basic Math Operations**

In [16]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [23]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])