<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.1+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.43964009, 0.49364935, 0.35326777, 0.365042  , 0.42704762],
        [0.64244857, 0.51534889, 0.10489257, 0.44521648, 0.3836991 ],
        [0.90840217, 0.70173556, 0.81278947, 0.37815286, 0.05592542],
        [0.08655668, 0.00305081, 0.85854099, 0.57720618, 0.26042843],
        [0.02918901, 0.46460569, 0.51664208, 0.04485946, 0.73849502]],

       [[0.20829142, 0.23795253, 0.51481511, 0.08710223, 0.87895792],
        [0.89925622, 0.20111599, 0.27711792, 0.27733896, 0.31968132],
        [0.18892444, 0.40874301, 0.14009903, 0.18440064, 0.79580007],
        [0.69783442, 0.29279392, 0.81836366, 0.00409571, 0.83555723],
        [0.38195129, 0.88022893, 0.85761847, 0.41379457, 0.52066184]],

       [[0.49197493, 0.82696491, 0.43573354, 0.56342373, 0.15320451],
        [0.21006536, 0.76380526, 0.38506228, 0.06308692, 0.4234943 ],
        [0.12361332, 0.29745894, 0.0898349 , 0.09770054, 0.96377387],
        [0.08697015, 0.25248038, 0.41326694, 0.27561093, 0.77051774],
        [0.87954

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [7]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [8]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d * 10)

tensor_2d
 tensor([[7.6257, 5.5807, 5.1118, 4.9280],
        [3.6901, 0.0955, 4.9299, 1.7102],
        [3.4505, 9.4647, 8.6870, 4.1594]])


In [9]:
testing = torch.tensor([1,2.,3],  requires_grad=True, device=torch.device('cpu'))
threads = torch.get_num_threads()
print('Number of threads :',threads)
testing

Number of threads : 1


tensor([1., 2., 3.], requires_grad=True)

In [10]:
check_grad = torch.is_grad_enabled()
print(check_grad)
torch.no_grad()
print(torch.is_grad_enabled())


True
True


In [11]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.4396, 0.4936, 0.3533, 0.3650, 0.4270],
         [0.6424, 0.5153, 0.1049, 0.4452, 0.3837],
         [0.9084, 0.7017, 0.8128, 0.3782, 0.0559],
         [0.0866, 0.0031, 0.8585, 0.5772, 0.2604],
         [0.0292, 0.4646, 0.5166, 0.0449, 0.7385]],

        [[0.2083, 0.2380, 0.5148, 0.0871, 0.8790],
         [0.8993, 0.2011, 0.2771, 0.2773, 0.3197],
         [0.1889, 0.4087, 0.1401, 0.1844, 0.7958],
         [0.6978, 0.2928, 0.8184, 0.0041, 0.8356],
         [0.3820, 0.8802, 0.8576, 0.4138, 0.5207]],

        [[0.4920, 0.8270, 0.4357, 0.5634, 0.1532],
         [0.2101, 0.7638, 0.3851, 0.0631, 0.4235],
         [0.1236, 0.2975, 0.0898, 0.0977, 0.9638],
         [0.0870, 0.2525, 0.4133, 0.2756, 0.7705],
         [0.8795, 0.9064, 0.4223, 0.8062, 0.6766]]], dtype=torch.float64)

In [13]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [14]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [15]:
r = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(r[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])

tensor(4)
[[0.1188192  0.55130186 0.87172378]
 [0.80162719 0.79078104 0.74249843]]
0.7907810398712574
tensor(0.7908, dtype=torch.float64)


In [16]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.51807096 0.23716001 0.53519   ]
 [0.79894202 0.1640777  0.82753894]]
0.1640777042956898
tensor(0.1641, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [17]:
x = torch.tensor([[1]])
x
x.item()

1

In [18]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [19]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [20]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


In [21]:
gpu
gpu = torch.device('cuda:0')
gpu

device(type='cuda', index=0)

**Basic Math Operations**

In [22]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [23]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])

In [24]:
my_tensor = torch.randn(3)
print(my_tensor)
my_tensor = torch.mul(my_tensor, 100)
my_tensor = torch.abs(my_tensor)    # Get the absolute value
# my_tensor = torch.mul(my_tensor, 100)
# my_tensor
print('Rounded values : ',torch.round(my_tensor))
torch.max(my_tensor)

tensor([-0.9271,  2.0423, -1.1030])
Rounded values :  tensor([ 93., 204., 110.])


tensor(204.2307)

In [25]:
prod_this = torch.tensor([1,2,3,4,5])
torch.prod(prod_this)
seven20 = torch.arange(1,7)
seven20
print(torch.prod(seven20))

# count non-zero
print(torch.count_nonzero(prod_this))


tensor(720)
tensor(5)


Sort

In [26]:
torch.sort(prod_this, descending=False)     #descending=False we can change it to True

torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 1, 2, 3, 4]))

In [27]:
torch.tensor([1,2,3,4,5,6]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
torch.cuda.get_device_properties(torch.cuda.get_device_name)

torch.cuda.get_device_capability(torch.cuda.get_device_name)
torch.cuda.is_available()
torch.cuda.is_initialized()
print('memory allocated : ',torch.cuda.memory_allocated())
print('memory usage: ', torch.cuda.memory_cached)
torch.cuda.power_draw

memory allocated :  512
memory usage:  <function memory_cached at 0x78f0f0be24d0>


<function torch.cuda.power_draw(device: Union[torch.device, str, int, NoneType] = None) -> int>

In [29]:
a = torch.tensor(torch.rand(50))

shape = torch.reshape(a, (5,10))
shape.shape

<ipython-input-29-0d7fd5271b5f>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(torch.rand(50))


torch.Size([5, 10])

**CPU**

In [30]:
torch.cpu.current_device()
torch.cpu.device_count

<function torch.cpu.device_count() -> int>

In [31]:
y_arr = torch.tensor([[15,12],[12,8]])
print(y_arr)

tensor([[15, 12],
        [12,  8]])


In [32]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [33]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)


100%|██████████| 26421880/26421880 [00:02<00:00, 11314310.48it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 170970.40it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3088768.87it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 5197948.24it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [34]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


**Creating Models**

In [37]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)    #move to GPU
print(model)


Using cuda device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


**!!! Pytorch Practice Session Covered all the necessary basic operations in Pytorch Library  !!!**