<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import torch
import numpy as np

**Pytorch basics**

In [54]:
print(torch.__version__)

2.4.0+cu121


In [55]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.39755522, 0.58590926, 0.57675506, 0.53657486, 0.67730892],
        [0.98355243, 0.54256329, 0.31170241, 0.46204504, 0.78484477],
        [0.69620897, 0.30114593, 0.49875668, 0.49843903, 0.61860226],
        [0.18629689, 0.4383667 , 0.13747234, 0.13001052, 0.30424569],
        [0.52854508, 0.19943045, 0.55763724, 0.81016927, 0.73084296]],

       [[0.49540269, 0.35246505, 0.79024929, 0.47144528, 0.49766218],
        [0.44019693, 0.8772274 , 0.78157454, 0.57382252, 0.23021871],
        [0.15536411, 0.17911006, 0.503634  , 0.05367847, 0.6876835 ],
        [0.70434541, 0.03940617, 0.69606606, 0.7107617 , 0.86332908],
        [0.81314642, 0.75437727, 0.86524331, 0.89935768, 0.05079436]],

       [[0.78495915, 0.2755306 , 0.44998434, 0.3244985 , 0.17092639],
        [0.49940486, 0.81217515, 0.80282113, 0.53450783, 0.68204477],
        [0.65512786, 0.71042876, 0.16084603, 0.37214299, 0.62109294],
        [0.44302633, 0.07235766, 0.70303672, 0.73618374, 0.82163723],
        [0.18000

In [56]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [58]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d)

tensor_2d
 tensor([[0.5420, 0.5763, 0.2594, 0.9686],
        [0.3200, 0.7425, 0.0608, 0.3096],
        [0.6507, 0.8307, 0.5461, 0.1431]])


In [59]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [60]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.3976, 0.5859, 0.5768, 0.5366, 0.6773],
         [0.9836, 0.5426, 0.3117, 0.4620, 0.7848],
         [0.6962, 0.3011, 0.4988, 0.4984, 0.6186],
         [0.1863, 0.4384, 0.1375, 0.1300, 0.3042],
         [0.5285, 0.1994, 0.5576, 0.8102, 0.7308]],

        [[0.4954, 0.3525, 0.7902, 0.4714, 0.4977],
         [0.4402, 0.8772, 0.7816, 0.5738, 0.2302],
         [0.1554, 0.1791, 0.5036, 0.0537, 0.6877],
         [0.7043, 0.0394, 0.6961, 0.7108, 0.8633],
         [0.8131, 0.7544, 0.8652, 0.8994, 0.0508]],

        [[0.7850, 0.2755, 0.4500, 0.3245, 0.1709],
         [0.4994, 0.8122, 0.8028, 0.5345, 0.6820],
         [0.6551, 0.7104, 0.1608, 0.3721, 0.6211],
         [0.4430, 0.0724, 0.7030, 0.7362, 0.8216],
         [0.1800, 0.8410, 0.8103, 0.9496, 0.9813]]], dtype=torch.float64)

In [61]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [62]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [63]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.15101969 0.88028255 0.15212999]
 [0.48920596 0.79878764 0.21123824]]
0.7987876407764521
tensor(0.7988, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [64]:
x = torch.tensor([[1]])
x
x.item()

1

In [65]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [66]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [67]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


**Basic Math Operations**

In [68]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])
