<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.1+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]    # this is a typical python list.
                              # Neither a numpy array nor a tensor

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.24350039, 0.89740057, 0.35552383, 0.27720022, 0.77343287],
        [0.10789866, 0.97681907, 0.13911476, 0.89173613, 0.96833056],
        [0.87446435, 0.60660533, 0.62303272, 0.95166338, 0.56783482],
        [0.62556021, 0.14675165, 0.85685185, 0.49635456, 0.57783601],
        [0.69038104, 0.59781319, 0.78913867, 0.90054322, 0.7989546 ]],

       [[0.00330546, 0.16716051, 0.90094753, 0.92947013, 0.44530469],
        [0.65742639, 0.10741696, 0.90692787, 0.37806293, 0.54514109],
        [0.55105236, 0.91531478, 0.15486338, 0.41298972, 0.10870563],
        [0.99157783, 0.13472489, 0.28314195, 0.41361577, 0.9308612 ],
        [0.72747387, 0.69140607, 0.57102991, 0.69933895, 0.23755148]],

       [[0.61571535, 0.52965727, 0.22669877, 0.55386192, 0.84645397],
        [0.34332379, 0.2845847 , 0.2093059 , 0.8227076 , 0.46522213],
        [0.89956596, 0.68683167, 0.83820936, 0.53468113, 0.41122383],
        [0.67613136, 0.53895001, 0.97398826, 0.89348635, 0.80121024],
        [0.74646

In [39]:
np2 = 100 * np.random.rand(2,3)
np2 = np.array(np2, dtype=int)
np2

array([[97, 56,  3],
       [63, 11,  0]])

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [7]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [8]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d * 10)

tensor_2d
 tensor([[9.2445, 5.5311, 8.9571, 2.4774],
        [5.0873, 4.7398, 2.4970, 6.1052],
        [3.8018, 9.3663, 9.7197, 4.0758]])


In [9]:
testing = torch.tensor([1,2.,3],  requires_grad=True, device=torch.device('cpu'))
threads = torch.get_num_threads()
print('Number of threads :',threads)
testing

Number of threads : 1


tensor([1., 2., 3.], requires_grad=True)

In [10]:
check_grad = torch.is_grad_enabled()
print(check_grad)
torch.no_grad()
print(torch.is_grad_enabled())


True
True


In [11]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.2435, 0.8974, 0.3555, 0.2772, 0.7734],
         [0.1079, 0.9768, 0.1391, 0.8917, 0.9683],
         [0.8745, 0.6066, 0.6230, 0.9517, 0.5678],
         [0.6256, 0.1468, 0.8569, 0.4964, 0.5778],
         [0.6904, 0.5978, 0.7891, 0.9005, 0.7990]],

        [[0.0033, 0.1672, 0.9009, 0.9295, 0.4453],
         [0.6574, 0.1074, 0.9069, 0.3781, 0.5451],
         [0.5511, 0.9153, 0.1549, 0.4130, 0.1087],
         [0.9916, 0.1347, 0.2831, 0.4136, 0.9309],
         [0.7275, 0.6914, 0.5710, 0.6993, 0.2376]],

        [[0.6157, 0.5297, 0.2267, 0.5539, 0.8465],
         [0.3433, 0.2846, 0.2093, 0.8227, 0.4652],
         [0.8996, 0.6868, 0.8382, 0.5347, 0.4112],
         [0.6761, 0.5390, 0.9740, 0.8935, 0.8012],
         [0.7465, 0.9843, 0.6820, 0.3886, 0.7376]]], dtype=torch.float64)

In [13]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [14]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [15]:
r = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(r[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])

tensor(4)
[[0.72190302 0.57379345 0.00941467]
 [0.83576679 0.5090462  0.50437538]]
0.5090461961552345
tensor(0.5090, dtype=torch.float64)


In [16]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.61929098 0.14426551 0.73015281]
 [0.69639608 0.83669875 0.57916938]]
0.8366987531326655
tensor(0.8367, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [17]:
x = torch.tensor([[1]])
x
x.item()

1

In [18]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [19]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [20]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


In [21]:
gpu
gpu = torch.device('cuda:0')
gpu

device(type='cuda', index=0)

**Basic Math Operations**

In [22]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [23]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])

In [24]:
my_tensor = torch.randn(3)
print(my_tensor)
my_tensor = torch.mul(my_tensor, 100)
my_tensor = torch.abs(my_tensor)    # Get the absolute value
# my_tensor = torch.mul(my_tensor, 100)
# my_tensor
print('Rounded values : ',torch.round(my_tensor))
torch.max(my_tensor)

tensor([-0.2470, -0.1639, -1.1384])
Rounded values :  tensor([ 25.,  16., 114.])


tensor(113.8373)

In [25]:
prod_this = torch.tensor([1,2,3,4,5])
torch.prod(prod_this)
seven20 = torch.arange(1,7)
seven20
print(torch.prod(seven20))

# count non-zero
print(torch.count_nonzero(prod_this))


tensor(720)
tensor(5)


Sort

In [26]:
torch.sort(prod_this, descending=False)     #descending=False we can change it to True

torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 1, 2, 3, 4]))

In [27]:
torch.tensor([1,2,3,4,5,6]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
torch.cuda.get_device_properties(torch.cuda.get_device_name)

torch.cuda.get_device_capability(torch.cuda.get_device_name)
torch.cuda.is_available()
torch.cuda.is_initialized()
print('memory allocated : ',torch.cuda.memory_allocated())
print('memory usage: ', torch.cuda.memory_cached)
torch.cuda.power_draw

memory allocated :  512
memory usage:  <function memory_cached at 0x7aca0c0d24d0>


<function torch.cuda.power_draw(device: Union[torch.device, str, int, NoneType] = None) -> int>

In [29]:
a = torch.tensor(torch.rand(50))

shape = torch.reshape(a, (5,10))
shape.shape

<ipython-input-29-0d7fd5271b5f>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(torch.rand(50))


torch.Size([5, 10])

**CPU**

In [30]:
torch.cpu.current_device()
torch.cpu.device_count

<function torch.cpu.device_count() -> int>

In [31]:
y_arr = torch.tensor([[15,12],[12,8]])
print(y_arr)

tensor([[15, 12],
        [12,  8]])


In [32]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [33]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)


100%|██████████| 26421880/26421880 [00:12<00:00, 2105479.13it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 178648.05it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3220046.78it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 21463496.02it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [34]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


**Creating Models**

In [35]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)    #move to GPU
print(model)


Using cuda device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


**!!! Pytorch Practice Session Covered all the necessary basic operations in Pytorch Library  !!!**