<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import torch
import numpy as np

**Pytorch basics**

In [91]:
print(torch.__version__)

2.4.1+cu121


In [92]:
mylist = [[1,2,3],[4,5,6]]    # this is a typical python list.
                              # Neither a numpy array nor a tensor

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.39495268, 0.83815573, 0.21610509, 0.66351101, 0.45895054],
        [0.84319445, 0.20499561, 0.37202374, 0.58551588, 0.40703247],
        [0.24806147, 0.01977322, 0.57795453, 0.28133574, 0.48385929],
        [0.9215345 , 0.89179061, 0.43109999, 0.52859502, 0.03037878],
        [0.62030068, 0.79748269, 0.71492142, 0.74173978, 0.86629411]],

       [[0.22531842, 0.59981654, 0.03443702, 0.72987974, 0.34995965],
        [0.21782257, 0.91776887, 0.17687615, 0.65933108, 0.51148224],
        [0.78562531, 0.04731341, 0.50257556, 0.85535337, 0.3180482 ],
        [0.85302408, 0.70539444, 0.5751464 , 0.3048853 , 0.6394438 ],
        [0.25621318, 0.32255039, 0.87396097, 0.58223039, 0.82151314]],

       [[0.25864141, 0.83390979, 0.65695625, 0.36558913, 0.25101023],
        [0.69447067, 0.7034484 , 0.89733058, 0.09149562, 0.90816662],
        [0.15880646, 0.81671376, 0.88580967, 0.67381947, 0.67408133],
        [0.00674241, 0.49366765, 0.8150061 , 0.96317565, 0.54446506],
        [0.54081

In [93]:
np2 = 100 * np.random.rand(2,3)
np2 = np.array(np2, dtype=int)
np2

array([[19, 62, 25],
       [57, 64, 27]])

In [94]:
test1 = np.random.rand(4) * 10
test1.reshape(2,2)

array([[7.05593342, 8.73151255],
       [9.71734567, 4.23189453]])

In [95]:
test2 = np.array([1,2,3,4,5,6])
test2

my_device = torch.cpu.current_device()
my_device

'cpu'

In [96]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [97]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [98]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [99]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [100]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d * 10)

tensor_2d
 tensor([[4.8273, 3.0898, 6.2797, 6.2945],
        [7.2349, 0.5989, 7.2704, 5.9118],
        [0.9042, 2.7294, 3.5168, 6.7117]])


In [101]:
testing = torch.tensor([1,2.,3],  requires_grad=True, device=torch.device('cpu'))
threads = torch.get_num_threads()
print('Number of threads :',threads)
testing

Number of threads : 1


tensor([1., 2., 3.], requires_grad=True)

In [102]:
check_grad = torch.is_grad_enabled()
print(check_grad)
torch.no_grad()
print(torch.is_grad_enabled())


True
True


In [103]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [104]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.3950, 0.8382, 0.2161, 0.6635, 0.4590],
         [0.8432, 0.2050, 0.3720, 0.5855, 0.4070],
         [0.2481, 0.0198, 0.5780, 0.2813, 0.4839],
         [0.9215, 0.8918, 0.4311, 0.5286, 0.0304],
         [0.6203, 0.7975, 0.7149, 0.7417, 0.8663]],

        [[0.2253, 0.5998, 0.0344, 0.7299, 0.3500],
         [0.2178, 0.9178, 0.1769, 0.6593, 0.5115],
         [0.7856, 0.0473, 0.5026, 0.8554, 0.3180],
         [0.8530, 0.7054, 0.5751, 0.3049, 0.6394],
         [0.2562, 0.3226, 0.8740, 0.5822, 0.8215]],

        [[0.2586, 0.8339, 0.6570, 0.3656, 0.2510],
         [0.6945, 0.7034, 0.8973, 0.0915, 0.9082],
         [0.1588, 0.8167, 0.8858, 0.6738, 0.6741],
         [0.0067, 0.4937, 0.8150, 0.9632, 0.5445],
         [0.5408, 0.9410, 0.8577, 0.1487, 0.3736]]], dtype=torch.float64)

In [128]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [138]:
if torch.cuda.is_available():
  #print('No cuda device found')
  #print(torch.cpu.current_device())
  print(torch.cuda.get_device_name())
else:
  print('Current device :',torch.cpu.current_device())
  print('CPU available :',torch.cpu.is_available())

Current device : cpu
CPU available : True


In [106]:
if torch.cuda.is_available():
  torch.ones([4,4], dtype=torch.float64, device=cuda0)
else:
  print('no GPU found')

no GPU found


Content can be accessed and modified using slice and indexing

In [107]:
r = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(r[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])

tensor(4)
[[0.92663695 0.91398391 0.79986664]
 [0.44383698 0.79019601 0.44914811]]
0.7901960085286751
tensor(0.7902, dtype=torch.float64)


In [108]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.53688903 0.41272772 0.72920852]
 [0.21424931 0.22231966 0.57440733]]
0.2223196613758115
tensor(0.2223, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [109]:
x = torch.tensor([[1]])
x
x.item()

1

In [110]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [111]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [112]:
#gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
  print('current device : ', torch.cuda.current_device())
  print('device count : ', torch.cuda.device_count())
  print('device name is : ', torch.cuda.get_device_name())
  device = torch.device('cuda:0')
  print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


In [113]:
#gpu
#gpu = torch.device('cuda:0')
#gpu

**Basic Math Operations**

In [114]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [115]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])

In [116]:
my_tensor = torch.randn(3)
print(my_tensor)
my_tensor = torch.mul(my_tensor, 100)
my_tensor = torch.abs(my_tensor)    # Get the absolute value
# my_tensor = torch.mul(my_tensor, 100)
# my_tensor
print('Rounded values : ',torch.round(my_tensor))
torch.max(my_tensor)

tensor([-0.2566,  0.4819,  0.1692])
Rounded values :  tensor([26., 48., 17.])


tensor(48.1878)

In [117]:
prod_this = torch.tensor([1,2,3,4,5])
torch.prod(prod_this)
seven20 = torch.arange(1,7)
seven20
print(torch.prod(seven20))

# count non-zero
print(torch.count_nonzero(prod_this))


tensor(720)
tensor(5)


Sort

In [118]:
torch.sort(prod_this, descending=False)     #descending=False we can change it to True

torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5]),
indices=tensor([0, 1, 2, 3, 4]))

In [119]:
torch.tensor([1,2,3,4,5,6]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [120]:
if torch.cuda.is_available():
  torch.cuda.get_device_properties(torch.cuda.get_device_name)

  torch.cuda.get_device_capability(torch.cuda.get_device_name)
  torch.cuda.is_available()
  torch.cuda.is_initialized()
  print('memory allocated : ',torch.cuda.memory_allocated())
  print('memory usage: ', torch.cuda.memory_cached)
  torch.cuda.power_draw

In [121]:
a = torch.tensor(torch.rand(50))

shape = torch.reshape(a, (5,10))
shape.shape

<ipython-input-121-0d7fd5271b5f>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  a = torch.tensor(torch.rand(50))


torch.Size([5, 10])

**CPU**

In [122]:
torch.cpu.current_device()
torch.cpu.device_count

<function torch.cpu.device_count() -> int>

In [123]:
y_arr = torch.tensor([[15,12],[12,8]])
print(y_arr)

tensor([[15, 12],
        [12,  8]])


In [124]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [125]:
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)


100%|██████████| 26421880/26421880 [00:05<00:00, 4996639.28it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 136701.41it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:06<00:00, 683032.84it/s] 


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 14708635.55it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [126]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


**Creating Models**

In [127]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)    #move to GPU
print(model)


Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


**!!! Pytorch Practice Session Covered all the necessary basic operations in Pytorch Library  !!!**