<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import torch
import numpy as np

**Pytorch basics**

In [32]:
print(torch.__version__)

2.4.0+cu121


In [98]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.14878232, 0.51995195, 0.5372453 , 0.8421185 , 0.62788477],
        [0.70799647, 0.8986185 , 0.35233012, 0.83692295, 0.38518196],
        [0.07949271, 0.39316461, 0.40451117, 0.1958874 , 0.26847792],
        [0.58334329, 0.54615461, 0.40874057, 0.51085056, 0.34783488],
        [0.09349139, 0.15692435, 0.7491777 , 0.78890084, 0.06179308]],

       [[0.46491066, 0.17075864, 0.5019215 , 0.69122951, 0.37344875],
        [0.02353678, 0.05479523, 0.56988211, 0.15816782, 0.90194385],
        [0.39854364, 0.97035062, 0.97271087, 0.72070506, 0.27425568],
        [0.58951986, 0.69093879, 0.61700405, 0.79038165, 0.03849403],
        [0.62015621, 0.64870342, 0.27776984, 0.45401068, 0.46999572]],

       [[0.26657119, 0.86400167, 0.02855404, 0.95870415, 0.99776147],
        [0.47542067, 0.89154669, 0.23730246, 0.92494414, 0.50297192],
        [0.6727945 , 0.5550669 , 0.14319591, 0.0470289 , 0.8656036 ],
        [0.90593457, 0.26476324, 0.17776869, 0.0442377 , 0.93964095],
        [0.32814

In [109]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [88]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [105]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d)

tensor_2d
 tensor([[0.3666, 0.7056, 0.9145, 0.1396],
        [0.6935, 0.4372, 0.3884, 0.1378],
        [0.8472, 0.8961, 0.9073, 0.4691]])


In [36]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [37]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[0.6678, 0.2517, 0.9028, 0.2324],
        [0.2780, 0.2072, 0.5131, 0.3915],
        [0.5139, 0.1293, 0.0069, 0.7351]], dtype=torch.float64)

In [38]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3], dtype=torch.int32)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
print(cuda0)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
cuda:0


In [39]:
#Content can be accessed and modified using python slicing and indexing notations
x = torch.tensor([[1,2,3], [4,5,6]])
y = np.array([1,2,4])
y

array([1, 2, 4])

In [40]:
import math

In [41]:
myl = np.array([[2,2,3,4,5],
                [2,2,3,4,5]])

myl.ndim #Return number of dimensions
myl.shape # Return number of elements in each dimension   (2,5)
len(myl.shape) == myl.ndim  # Is it the same as no. of dimensions?
myl.size   # Total number of elements  (10)
math.prod(myl.shape) == myl.size    # no. of elements is each dimension * no. of dimensions

myl.dtype


dtype('int64')

**Create a basic array**

In [42]:
array = np.zeros([2,3])
array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
array_ones = np.ones([3,2], dtype=int)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [44]:
# Empty array
array_emt = np.empty(3)  #Because of speed
array_emt

array([4.91558068e-310, 0.00000000e+000, 0.00000000e+000])

In [45]:
# Range of elements
print((np.ones([3,3])).size)


9
