<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**Pytorch basics**

In [2]:
print(torch.__version__)

2.4.0+cu121


In [3]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.63175565, 0.25736587, 0.71292652, 0.95395886, 0.00255328],
        [0.50322456, 0.59437801, 0.40508904, 0.72509567, 0.46828107],
        [0.48723259, 0.76174711, 0.69232546, 0.31889833, 0.00291574],
        [0.82837069, 0.46048736, 0.33814142, 0.72790425, 0.8843454 ],
        [0.09298812, 0.311042  , 0.36692919, 0.04949962, 0.79885983]],

       [[0.57428012, 0.11188757, 0.47984489, 0.05426771, 0.75616928],
        [0.85002244, 0.21940954, 0.22118677, 0.17692821, 0.39276293],
        [0.94097698, 0.67830123, 0.79160258, 0.61161332, 0.52416667],
        [0.80295261, 0.62931275, 0.44581699, 0.03705316, 0.00645083],
        [0.7233706 , 0.24285874, 0.37024817, 0.96592527, 0.21304995]],

       [[0.2167907 , 0.44931165, 0.43805811, 0.73207566, 0.31175042],
        [0.85886728, 0.47094352, 0.47757112, 0.62950804, 0.16386125],
        [0.65937186, 0.61728444, 0.37919833, 0.28135724, 0.55790516],
        [0.12386178, 0.48498089, 0.95491799, 0.81399837, 0.46541521],
        [0.57610

In [4]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [6]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d)

tensor_2d
 tensor([[0.6458, 0.7185, 0.7596, 0.5987],
        [0.6968, 0.9703, 0.3462, 0.5495],
        [0.4575, 0.0203, 0.2836, 0.3637]])


In [7]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.6318, 0.2574, 0.7129, 0.9540, 0.0026],
         [0.5032, 0.5944, 0.4051, 0.7251, 0.4683],
         [0.4872, 0.7617, 0.6923, 0.3189, 0.0029],
         [0.8284, 0.4605, 0.3381, 0.7279, 0.8843],
         [0.0930, 0.3110, 0.3669, 0.0495, 0.7989]],

        [[0.5743, 0.1119, 0.4798, 0.0543, 0.7562],
         [0.8500, 0.2194, 0.2212, 0.1769, 0.3928],
         [0.9410, 0.6783, 0.7916, 0.6116, 0.5242],
         [0.8030, 0.6293, 0.4458, 0.0371, 0.0065],
         [0.7234, 0.2429, 0.3702, 0.9659, 0.2130]],

        [[0.2168, 0.4493, 0.4381, 0.7321, 0.3118],
         [0.8589, 0.4709, 0.4776, 0.6295, 0.1639],
         [0.6594, 0.6173, 0.3792, 0.2814, 0.5579],
         [0.1239, 0.4850, 0.9549, 0.8140, 0.4654],
         [0.5761, 0.0505, 0.7853, 0.8097, 0.7580]]], dtype=torch.float64)

In [9]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [10]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [11]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.77551606 0.75296591 0.53494189]
 [0.00155351 0.24732465 0.56344855]]
0.24732464552127642
tensor(0.2473, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [12]:
x = torch.tensor([[1]])
x
x.item()

1

In [13]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [14]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [43]:
torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))

cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)
