<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

**Pytorch basics**

In [3]:
print(torch.__version__)

2.4.1+cu121


In [4]:
mylist = [[1,2,3],[4,5,6]]

#numpy array
np1 = np.random.rand(3,5,5) # Random.rand no [] brackets
np1


array([[[0.52518095, 0.9080784 , 0.04744659, 0.81714615, 0.85447892],
        [0.97752652, 0.36450438, 0.24064435, 0.83307847, 0.97966826],
        [0.26891848, 0.72542784, 0.56785289, 0.1480725 , 0.62662569],
        [0.17226977, 0.461206  , 0.78048457, 0.10511331, 0.73207163],
        [0.3254759 , 0.18097663, 0.88010056, 0.1988678 , 0.24481983]],

       [[0.82304907, 0.42729418, 0.89302436, 0.99019432, 0.83965796],
        [0.08343038, 0.04268423, 0.49890119, 0.08590193, 0.30338955],
        [0.20468176, 0.44703418, 0.22184682, 0.61859054, 0.26085941],
        [0.84263938, 0.68766476, 0.54575691, 0.80678214, 0.63373097],
        [0.24750293, 0.78819584, 0.11310593, 0.20299931, 0.56607514]],

       [[0.75774903, 0.67457264, 0.80442498, 0.50781194, 0.37844281],
        [0.71864627, 0.46836706, 0.96460989, 0.07369284, 0.74193153],
        [0.69451327, 0.11345866, 0.33342865, 0.48119576, 0.86914845],
        [0.1563592 , 0.90244465, 0.08328447, 0.85296946, 0.83336489],
        [0.21479

In [5]:
# Using ones and Zeros
ones = np.ones([2,3], dtype=int)  # Must need [] brackets in ones & zeros.
ones                              # dtype can be specified in np.ones and np.zeros

array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
print(np1.dtype)   # Random has no arguement as dtype
                   # Therefore always dtype=float64 (default)

float64


In [7]:
ar_ones = torch.ones(5)
print(ar_ones)
print('No. of elements : ', torch.numel(ar_ones))
torch.is_tensor(ar_ones)    # check whethr a tensor
torch.is_storage(ar_ones)   # not an storage - False
torch.is_nonzero(ar_ones[0])

tensor([1., 1., 1., 1., 1.])
No. of elements :  5


True

In [8]:
#torch.is_nonzero(ar_ones)
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-30-011fd7f163f7> in <cell line: 1>()
# ----> 1 torch.is_nonzero(ar_ones)

# RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [9]:
tensor_2d = torch.rand(3,4)   # Doesn't matter whether [] is present or not in TENSOR
tensor_2d

tensor2d = torch.rand([3,4])
print('tensor_2d\n', tensor2d * 10)

tensor_2d
 tensor([[1.0565, 0.8223, 8.7195, 3.3128],
        [5.1576, 4.5688, 9.6085, 2.5206],
        [3.2849, 3.6803, 4.9763, 5.8781]])


In [39]:
testing = torch.tensor([1,2.,3],  requires_grad=True, device=torch.device('cpu'))
threads = torch.get_num_threads()
print('Number of threads :',threads)
testing

Number of threads : 1


tensor([1., 2., 3.], requires_grad=True)

In [42]:
check_grad = torch.is_grad_enabled()
print(check_grad)
torch.no_grad()
print(torch.is_grad_enabled())


True
True


In [10]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[[0.5252, 0.9081, 0.0474, 0.8171, 0.8545],
         [0.9775, 0.3645, 0.2406, 0.8331, 0.9797],
         [0.2689, 0.7254, 0.5679, 0.1481, 0.6266],
         [0.1723, 0.4612, 0.7805, 0.1051, 0.7321],
         [0.3255, 0.1810, 0.8801, 0.1989, 0.2448]],

        [[0.8230, 0.4273, 0.8930, 0.9902, 0.8397],
         [0.0834, 0.0427, 0.4989, 0.0859, 0.3034],
         [0.2047, 0.4470, 0.2218, 0.6186, 0.2609],
         [0.8426, 0.6877, 0.5458, 0.8068, 0.6337],
         [0.2475, 0.7882, 0.1131, 0.2030, 0.5661]],

        [[0.7577, 0.6746, 0.8044, 0.5078, 0.3784],
         [0.7186, 0.4684, 0.9646, 0.0737, 0.7419],
         [0.6945, 0.1135, 0.3334, 0.4812, 0.8691],
         [0.1564, 0.9024, 0.0833, 0.8530, 0.8334],
         [0.2148, 0.3896, 0.0449, 0.2966, 0.7210]]], dtype=torch.float64)

In [12]:
#Create a tensor with specific data type
mytensor = torch.zeros([2,3],dtype=torch.int64)
mytensor

cuda0 = torch.device('cuda:0')
print(mytensor)
cuda0

tensor([[0, 0, 0],
        [0, 0, 0]])


device(type='cuda', index=0)

In [13]:
torch.ones([4,4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

Content can be accessed and modified using slice and indexing

In [14]:

x = torch.tensor([[1,2,3], [4,5,6]])
y = np.random.rand(2,3)
print(x[1][0])
print(y)
print(y[1][1])
z = torch.tensor(y)

print(z[1][1])


tensor(4)
[[0.99014219 0.69229524 0.94118544]
 [0.69197839 0.2653501  0.39462694]]
0.26535009578651236
tensor(0.2654, dtype=torch.float64)


Torch.tensor.item() :  get a Python number from a tensor containing a **single value**

In [15]:
x = torch.tensor([[1]])
x
x.item()

1

In [16]:
tnsr = torch.tensor([[1,-1],[1,1]],dtype=torch.float64, requires_grad=True)
tnsr

          # OR #
tnsr = torch.tensor([[1.,-1.],[1.,1.]], requires_grad=True)
tnsr

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [17]:
out = tnsr.pow(2).sum()
out.backward()
tnsr.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [18]:
gpu = torch.cpu.current_device()
cuda = torch.cuda.is_available()
if cuda == True:
  print('cuda is available')
print('current device : ', torch.cuda.current_device())
print('device count : ', torch.cuda.device_count())
print('device name is : ', torch.cuda.get_device_name())
device = torch.device('cuda:0')
print('device properties : ', torch.cuda.get_device_properties(device))
#print('Power drawn by GPU : ', torch.cuda.power_draw(device))


cuda is available
current device :  0
device count :  1
device name is :  Tesla T4
device properties :  _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)


**Basic Math Operations**

In [19]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([4,5,6,7])

print(torch.add(tensor_a, tensor_b))
print(torch.mul(tensor_a , tensor_b))
print(torch.divide(tensor_a , tensor_b))
print(torch.remainder(tensor_b, tensor_a))
print(torch.pow(tensor_a, tensor_b))

tensor([ 5,  7,  9, 11])
tensor([ 4, 10, 18, 28])
tensor([0.2500, 0.4000, 0.5000, 0.5714])
tensor([0, 1, 0, 3])
tensor([    1,    32,   729, 16384])


In [20]:
tens = torch.tensor([12,4,7])
tens
tens.shape

torch.Size([3])