<a href="https://colab.research.google.com/github/KalharaBatangala/Learn-pytorch/blob/main/Learn_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.4.0+cu121


In [27]:
mylist = [[1,2,3],[4,5,6]]


np1 = np.random.rand(3,4)
np1


array([[0.03537417, 0.00289237, 0.63428392, 0.72477867],
       [0.08484962, 0.5897789 , 0.70281749, 0.79880552],
       [0.32998325, 0.09015048, 0.81478014, 0.04599603]])

In [23]:
print(np1.dtype)

float64


In [31]:
tensor_2d = torch.rand(3,4)
print(tensor_2d.dtype)
tensor_2d


torch.float32


tensor([[0.3443, 0.5810, 0.8273, 0.2734],
        [0.1811, 0.2277, 0.4672, 0.1770],
        [0.1084, 0.8196, 0.5005, 0.2053]])

In [32]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d.dtype)
tensor_3d

torch.float32


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [33]:
#Create a tensor out of numpy array
mytensor = torch.tensor(np1)
mytensor

tensor([[0.0354, 0.0029, 0.6343, 0.7248],
        [0.0848, 0.5898, 0.7028, 0.7988],
        [0.3300, 0.0902, 0.8148, 0.0460]], dtype=torch.float64)